### ISSUE TITLE
changelog template header formatting

### ISSUE THREAD

**Issue by rennerom** [nomi9995/release-notes-cli#2]
Hey there,

I've been searching for simple changelog generator and found this to be quite ideal. I am wondering if you were intentionally formatting the changelog template to not include spaces between the hashes and the title? 

At first I was expecting something akin to this

>### Fix
>- update thing
>- fix that

But it is formatted as 

>###Fix
>- update thing
>- fix that

If intentional, that's fine, I'll work off my own fork. Else I'll send over a PR. Just let me know. Thanks!

**Comment by numandev1** [comment]
@rennerom thanks for pointing out this bug, I have fixed it, and now you can use `0.0.6` version
